#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ls after every cd
function chpwd() { ls }

# Enable dircolors
# TODO: Support BSD ls (i.e. macOS's)
if type dircolors >/dev/null && [[ -s $HOME/.dircolors ]]; then
    source <(dircolors $HOME/.dircolors)
    zstyle ':completion:*:default' list-colors "$LS_COLORS"
fi

# Aliases
alias vim=nvim
alias python=python3
alias pip='python3 -m pip'

# Read machine specific configuration
if [[ -s $HOME/.zshrc.machine ]]; then
    source $HOME/.zshrc.machine
fi
