#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ls after every cd
function chpwd() { ls }

# Enable dircolors
# TODO: Support BSD ls (i.e. macOS's)
if type dircolors >/dev/null && [[ -s $HOME/.dircolors ]]; then
    source <(dircolors $HOME/.dircolors)
    zstyle ':completion:*:default' list-colors "$LS_COLORS"
fi

# Initialize / activate python venv
function workon() {
    name=${1:-venv}
    if [ -f "$name/bin/activate" ]; then
        source "$name/bin/activate"
    elif [ ! -e $name ]; then
        python3 -m venv --system-site-packages $name \
            && source "$name/bin/activate"
    else
        echo "'$name' is not a venv directory" >&2
        return 1
    fi
}

# Aliases
if type "explorer.exe" >/dev/null; then
    alias open='explorer.exe'
fi
if type nvim >/dev/null; then
    alias vim=nvim
fi
# Fortunately, I never use python2.x
alias python=python3
alias pip='python3 -m pip'

# Read machine specific configuration
if [[ -s $HOME/.zshrc.machine ]]; then
    source $HOME/.zshrc.machine
fi

# List current directory
ls
